schema: 'packages/api/src/schema.graphql'
documents: 'packages/app/src/components/**/*.{tsx,ts}'
extensions:
    endpoints:
        example:
            url: 'https://rickandmortyapi.com'
    customExtension:
        foo: true
